# prod
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "team-a-kargo-test-prod"
  description: "team-a-kargo-test-prod"
  tags:
    - sx-cnp-oss
    - template
    - kargo
    - metalstack
    - kubex
  links:
    - url: http://team-a-kargo-test-prod.lab.suxessit.k8s.cloud.uibk.ac.at
      title: Prod Instance of team-a-kargo-test
      icon: web
  annotations:
    github.com/project-slug: suxess-it/team-a-kargo-test
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=kargo-test-prod'
    argocd/app-namespace: adn-team-a
    argocd/app-name: kargo-test-prod
    backstage.io/techdocs-ref: dir:.
    kargo-project: "https://kargo.lab.suxessit.k8s.cloud.uibk.ac.at/project/team-a-kargo-test-kargo-project"
    grafana/dashboard-selector: "(tags @> 'suXess')"
    grafana/overview-dashboard: "https://grafana.lab.suxessit.k8s.cloud.uibk.ac.at/d/k8s_views_ns/kubernetes-views-namespaces?orgId=1&refresh=30s&var-datasource=default&var-cluster=suxessit-uibklab&var-namespace=team-a-kargo-test-prod&var-resolution=30s&var-created_by=All"
spec:
  type: service
  lifecycle: prod
  owner: "team-a"
  system: kargo-test
  dependsOn:
    - resource:argocd
    - resource:kubecost
    - resource:grafana
    - resource:metalstack
    - resource:loki
    - resource:kyverno
    - resource:tempo
    - resource:backstage
  subcomponentOf: team-a-kargo-test
---
#qa
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "team-a-kargo-test-qa"
  description: "team-a-kargo-test-qa"
  tags:
    - sx-cnp-oss
    - template
    - kargo
    - metalstack
    - kubex
  links:
    - url: http://team-a-kargo-test-qa.lab.suxessit.k8s.cloud.uibk.ac.at
      title: QA Instance of team-a-kargo-test
      icon: web
  annotations:
    github.com/project-slug: suxess-it/team-a-kargo-test
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=kargo-test-qa'
    argocd/app-namespace: adn-team-a
    argocd/app-name: kargo-test-qa
    backstage.io/techdocs-ref: dir:.
    kargo-project: "https://kargo.lab.suxessit.k8s.cloud.uibk.ac.at/project/team-a-kargo-test-kargo-project"
    grafana/dashboard-selector: "(tags @> 'suXess')"
    grafana/overview-dashboard: "https://grafana.lab.suxessit.k8s.cloud.uibk.ac.at/d/k8s_views_ns/kubernetes-views-namespaces?orgId=1&refresh=30s&var-datasource=default&var-cluster=suxessit-uibklab&var-namespace=team-a-kargo-test-qa&var-resolution=30s&var-created_by=All"
spec:
  type: service
  lifecycle: qa
  owner: "team-a"
  system: kargo-test
  dependsOn:
    - resource:argocd
    - resource:kubecost
    - resource:grafana
    - resource:metalstack
    - resource:loki
    - resource:kyverno
    - resource:tempo
    - resource:backstage
  subcomponentOf: team-a-kargo-test
---
# test
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "team-a-kargo-test-test"
  description: "team-a-kargo-test-test"
  tags:
    - sx-cnp-oss
    - template
    - kargo
    - metalstack
    - kubex
  links:
    - url: http://team-a-kargo-test-test.lab.suxessit.k8s.cloud.uibk.ac.at
      title: Test Instance of team-a-kargo-test
      icon: web
  annotations:
    github.com/project-slug: suxess-it/team-a-kargo-test
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=kargo-test-test'
    argocd/app-namespace: adn-team-a
    argocd/app-name: kargo-test-test
    backstage.io/techdocs-ref: dir:.
    kargo-project: "https://kargo.lab.suxessit.k8s.cloud.uibk.ac.at/project/team-a-kargo-test-kargo-project"
    grafana/dashboard-selector: "(tags @> 'suXess')"
    grafana/overview-dashboard: "https://grafana.lab.suxessit.k8s.cloud.uibk.ac.at/d/k8s_views_ns/kubernetes-views-namespaces?orgId=1&refresh=30s&var-datasource=default&var-cluster=suxessit-uibklab&var-namespace=team-a-kargo-test-test&var-resolution=30s&var-created_by=All"
spec:
  type: service
  lifecycle: test
  owner: "team-a"
  system: kargo-test
  dependsOn:
    - resource:argocd
    - resource:kubecost
    - resource:grafana
    - resource:metalstack
    - resource:loki
    - resource:kyverno
    - resource:tempo
    - resource:backstage
  subcomponentOf: team-a-kargo-test
---
# main, at the end of catalog-info.yaml so that register link is on main component
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "team-a-kargo-test"
  description: "team-a-kargo-test"
  tags:
    - sx-cnp-oss
    - template
    - kargo
    - metalstack
    - kubex
  links:
    - url: https://argocd.lab.suxessit.k8s.cloud.uibk.ac.at/applications/adn-team-a/team-a-kargo-test?resource=
      title: ArgoCD Application Information of team-a-kargo-test
      icon: web
  annotations:
    github.com/project-slug: suxess-it/team-a-kargo-test
    backstage.io/kubernetes-label-selector: 'app.kubernetes.io/instance=team-a-kargo-test'
    argocd/app-namespace: adn-team-a
    argocd/app-name: team-a-kargo-test
    backstage.io/techdocs-ref: dir:.
    kargo-project: "https://kargo.lab.suxessit.k8s.cloud.uibk.ac.at/project/team-a-kargo-test-kargo-project"
    grafana/dashboard-selector: "(tags @> 'suXess')"
spec:
  type: service
  lifecycle: experimental
  owner: "team-a"
  system: kargo-test
  dependsOn:
    - resource:argocd
    - resource:kubecost
    - resource:grafana
    - resource:metalstack
    - resource:loki
    - resource:kyverno
    - resource:tempo
    - resource:backstage
---
